#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

function build:css {
  local args=()

  if [[ "${NODE_ENV:-}" == "production" ]]; then
    args=(--minify)
  else
    args=(--watch)
  fi

  npx tailwindcss --output ./styles/tailwind.css "${args[@]}"
}

function help {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-help}"
